### ISSUE TITLE
cwdaemon support

### ISSUE THREAD

**Issue by jmeloranta** [n4ogw/so2sdr#6]
This is not a bug but it would be great to have support for cwdaemon. I am using DTR keying via RS232 (the same cable as rig ctl) and cwdaemon works well for this.

ps. I am sure there is a way to mark this as suggestion in github but couldn't find that tag.

**Comment by n4ogw** [comment]
I will look into adding that.

Tor

**Comment by jmeloranta** [comment]
Thanks. The sequences for controlling cwdaemon are here: https://github.com/acerion/cwdaemon/blob/master/doc/specifications/escape_codes.txt

**Comment by jmeloranta** [comment]
Just noticed that you added cwdaemon support - works great! Thank you. I will close the ticket.
